In [1]:
import jax.numpy as jnp
import autograd.numpy as anp
import timeit

In [2]:
# Define some weight matrix and rates

W11 = 1.3
W21 = 0.7
W33 = 0.1 * W11
W43 = 0.1 * W21
W56 = -3*W11
W66 = -3*W21


Wjax = jnp.array([[W11, 0, 0, 0, 0, 0],[W21, 0, 0, 0, 0, 0], [0, 0, W33, 0, 0, 0], [0, 0, W43, 0, 0, 0], [0, 0, 0, 0, 0, W56], [0, 0, 0, 0, 0, W66]])
rjax = jnp.zeros((6,4))
Ijax = jnp.ones_like(rjax)

Wauto = anp.array([[W11, 0, 0, 0, 0, 0],[W21, 0, 0, 0, 0, 0], [0, 0, W33, 0, 0, 0], [0, 0, W43, 0, 0, 0], [0, 0, 0, 0, 0, W56], [0, 0, 0, 0, 0, W66]])
rauto = anp.zeros((6, 4))
Iauto = anp.ones_like(rauto)

dt = 0.1

/Users/cholt/Google Drive/Python/torch_SSN/jax/jax/lib/xla_bridge.py:109: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')


In [6]:
def drdt(r, W, I):
    dr = 0.5 * (abs(W @ r + I) + W @ r + I) #rectified linear units  
    return dr

def euler_update_jax(r, W, I):
    t = 0
    
    while t < 100:
        dr = drdt(r, W, I)
        r = r + dr * dt
        t += 1
    
    return r

def euler_update_auto(r, W, I):
    t = 0
    
    while t < 100:
        dr = drdt(r, W, I)
        r = r + dr * dt
        t += 1
    
    return r

    

In [7]:
%timeit euler_update_jax(rjax, Wjax, Ijax)
%timeit euler_update_auto(rauto, Wauto, Iauto)

85.2 ms ± 589 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
761 µs ± 8.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
rjax_final = euler_update_jax(rjax, Wjax, Ijax)
rauto_final = euler_update_auto(rauto, Wauto, Iauto)

# Chekc they give more or less the same answer 
print('Jax final - Auto final = ',rjax_final - rauto_final)

Jax final - Auto final =  [[-3.1250000e-02 -3.1250000e-02 -3.1250000e-02 -3.1250000e-02]
 [-2.3437500e-02 -2.3437500e-02 -2.3437500e-02 -2.3437500e-02]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.4901161e-08 -1.4901161e-08 -1.4901161e-08 -1.4901161e-08]
 [-2.9802322e-08 -2.9802322e-08 -2.9802322e-08 -2.9802322e-08]]
